### PR TITLE
Update AudioCapture.swift

### PR DESCRIPTION
**Pull request by DaveHineman**
Changes to init() to eliminate constant audio resets. .defaultToSpeaker and .mergeWithOthers added to improve compatibility with other plugins. I also added some code from the flutter audio_streams package that keeps the stream from dying when changing pages in an app (from https://pub.dev/packages/audio_streams).

### CODE REVIEW

**Comment by ysak-y** [comment]
Hi @DaveHineman !! Thank you for submitting PR!! btw, why did you close it? It seems good modification!!

**Comment by DaveHineman** [comment]
It’s my first pull request, so I wasn’t sure if I was the one to close it. I can do it. When will you be able to put out a new version?On Dec 16, 2022, at 8:55 PM, ymd ***@***.***> wrote:﻿
Hi @DaveHineman !! Thank you for submitting PR!! btw, why did you close it? It seems good modification!!

**Review by ysak-y — APPROVED** [review]

**Comment by ysak-y** [comment]
@DaveHineman Okay, I restored and approved this PR. Please click "Merge pull request" button.

**Comment by DaveHineman** [comment]
Sorry, there was only a ‘close pull request’ button. I clicked what looked like a ‘reload’ button by your name and then it said ‘resubmitting pull request.’

Looks like an accidentally closed this when I cleaned up my first pull attempts. I’ll start over.

**Review by DaveHineman — COMMENTED** [review]
Looks good to me.

**Comment by DaveHineman** [comment]
I really don't care about the credentials, feel free to just add the changes yourself and roll the version. Later I will learn how to do a pull request properly.

**Review by ysak-y — APPROVED** [review]

**Pull request closed without merging**
