### PR TITLE
General improvements and multithreading / start stop issues fixed

### PR DESCRIPTION
**Pull request by srmncnk**
This PR address general improvements and multithreading / start stop issues.

Please review and consider merging.

### CODE REVIEW

**Comment by srmncnk** [comment]
@ysak-y Can you please take a look at this and consider merging? Many thanks.

**Comment by ysak-y** [comment]
Hi @srmanc , thank you for your PR. I'll check until next Monday.

**Comment by ysak-y** [comment]
Checked. LGTM

**Comment by ysak-y** [comment]
Now I published new version v1.1.1 with your implementation. Thanks @srmanc !!
https://github.com/ysak-y/flutter_audio_capture/blob/master/CHANGELOG.md#111

**Comment by kijka** [comment]
@srmanc looks like there is an iOS issue https://github.com/ysak-y/flutter_audio_capture/issues/16
Do you have any ideas about what could be wrong?

**Comment by kijka** [comment]
@srmanc @ysak-y I've added a project to test and video demo of the bug to the https://github.com/ysak-y/flutter_audio_capture/issues/16

**Comment by ysak-y** [comment]
@srmanc What do you think about #16 ? As @vladsonkin reports, it seems be disabled after some time, and I guess it would be because of multithreading.

**Comment by srmncnk** [comment]
@vladsonkin @ysak-y Thanks for the reproducible example, I'll take a look this weekend.

**Comment by kijka** [comment]
@srmanc Thanks! Any ideas on how to fix it? Maybe it's the init block in SwiftFlutterAudioCapturePlugin?

**Comment by srmncnk** [comment]
Prepared a PR, please test it: https://github.com/ysak-y/flutter_audio_capture/pull/19

**Pull request merged**
